In [2]:
import numpy as np

In [7]:
array1= np.array([1,2,3,4,5])#1-D array

In [4]:
#2-D array
array2 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])

In [4]:
print(array1)

[1 2 3 4 5]


In [5]:
print(array2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
#3-D array
array3= np.array([[
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15]
],
                 [
                     [16,17,18,19,20],
                     [21,22,23,24,25],
                     [26,27,28,29,30]
                 ]])

In [8]:
print(array3)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]

 [[16 17 18 19 20]
  [21 22 23 24 25]
  [26 27 28 29 30]]]


In [13]:
array4=np.zeros(5)

In [14]:
print(array4)

[0. 0. 0. 0. 0.]


In [15]:
array5=np.zeros((5,4))

In [16]:
print(array5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [17]:
array6=np.zeros((4,3,2))

In [18]:
print(array6)

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [19]:
array7 = np.ones(5)

In [20]:
print(array7)

[1. 1. 1. 1. 1.]


In [22]:
array8 = np.arange(1,12)

In [23]:
print(array8)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [24]:
array9 = np.linspace(1,10)

In [25]:
print(array9)

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [34]:
array10 = np.linspace(1,10,10)

In [35]:
print(array10)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [36]:
array11 = np.linspace(1,10,2)# here the 2 is the steps to reach the 10 
#so if we write 20 steps then the no. will be in decimal to reach to the number 10

In [37]:
print(array11)

[ 1. 10.]


In [40]:
array12 = np.linspace(1,10,20)

In [41]:
print(array12)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [43]:
array3.ndim#to check the dimensions of the array

3

In [47]:
array3.shape#in array3 there are two 2-D arrays and in that 2-D array it has 3 rows and 5 columns

(2, 3, 5)

In [56]:
array2.shape

(2, 5)

In [48]:
array3.size # no. of items in array

30

In [49]:
array3.dtype# tells the data type of the items

dtype('int64')

In [50]:
list1 = [1,2,3,4,5]

In [51]:
arraylist=np.array(list1)

In [52]:
print(arraylist)

[1 2 3 4 5]


In [53]:
#vector function
array2 * 2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [55]:
print(array2)
print(array2 * 2)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [61]:
array1[0] # to access the specific element

np.int64(1)

In [63]:
array2[1][2] # normal indexing

np.int64(8)

In [64]:
array2[1,2]# fancy indexing

np.int64(8)

In [65]:
array2[1,2] * array2[0,3]

np.int64(32)

In [16]:
array2 * array2 #to multiply two arrays(this is called vectorization)

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [67]:
array2 ** 2 # to take square of all elements

array([[  1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100]])

In [17]:
#to multiply two arrays with different dimension but the no. of columns should be same this is called broadcasting
print(array1)
print("________________")
print(array2)
print("__________________")
print(array1*array2)

[1 2 3 4 5]
________________
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
__________________
[[ 1  4  9 16 25]
 [ 6 14 24 36 50]]


In [29]:
np.sum(array3)#to take sum of all elements

np.int64(465)

In [30]:
np.prod(array1)#to take product of all elements

np.int64(120)

In [3]:
array20 = np.zeros((3,4))

In [4]:
array20

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
type(array20[0,1])

numpy.float64

In [ ]:
array20[1,2]=25

In [15]:
array20

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0., 25.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
array20[2,3]=36

In [19]:
array20

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0., 25.,  0.],
       [ 0.,  0.,  0., 36.]])

In [20]:
np.sum(array20)

np.float64(61.0)

In [31]:
np.prod(array20)

np.float64(0.0)

In [22]:
array21 = np.ones((3,4))

In [23]:
array21

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
array21[2,1] = 25

In [25]:
array21[1,2] = 36

In [26]:
np.sum(array21)

np.float64(71.0)

In [32]:
np.prod(array21)

np.float64(900.0)

In [6]:
list2 = [33,44,55,66,77]# to convsert list into array all the list contains elements that has same data type

In [7]:
array22 = np.array(list2)

In [8]:
array22

array([33, 44, 55, 66, 77])

In [10]:
#if the list have string element and integer element so the array converts the integer elments to string
list3 = [3,4,5,'ring','king']
array23 = np.array(list3)
array23

array(['3', '4', '5', 'ring', 'king'], dtype='<U21')

In [11]:
array23[0]*4

'3333'

In [12]:
array23[0]+4 # so we cannot add the string with no. so for that we do typecasting

TypeError: can only concatenate str (not "int") to str

In [14]:
# if the element in array23 is no. then we convert it to int as all elements are string and if it is string then give exception(takes more time)
try:
    value = int(input('enter index'))
    try:
        print(int(array23[value]))
    except ValueError:
        print(array23[value])
except ValueError:
    print("index must be integer")
except IndexError:
    print('enter proper index')

enter index 3


ring


In [52]:
#method 2 that saves time
nums=[]
for i in list3:
    try:
        nums.append(float(i))
    except:
        pass

In [53]:
nums

[3.0, 4.0, 5.0]

In [58]:
#challenge in method2 - it gives 1ef, NaN, inf as output because in python these all are numbers here e means 1000
list4 = ['1e3', '3','4','NaN','inf']
nums2=[]
for i in list4:
    try:
        nums2.append(float(i))
    except:
        pass
print(nums2)

[1000.0, 3.0, 4.0, nan, inf]


In [57]:
# to solve this
list5 = ['1e3', '3','4','NaN','inf']
nums3=[]
for i in list5:
    try:
        val = float(i)
        if not (val == float('1e3') or val == float('inf') or val == float('-inf') or val != val):
                nums3.append(val)
    except:
        pass
print(nums3)

[3.0, 4.0]


In [63]:
# to convert 1 D array into 2 D array
array25 = np.array([1,2,3,4,4,56,7,42,22,546,1,12,5,15,62,25,25,24])

In [64]:
array25.size

18

In [65]:
array25.reshape(3,6)

array([[  1,   2,   3,   4,   4,  56],
       [  7,  42,  22, 546,   1,  12],
       [  5,  15,  62,  25,  25,  24]])

In [66]:
array25.reshape(2,9)

array([[  1,   2,   3,   4,   4,  56,   7,  42,  22],
       [546,   1,  12,   5,  15,  62,  25,  25,  24]])

In [67]:
# to convert 1-D array into 3-D array
array25.reshape(2,3,3)

array([[[  1,   2,   3],
        [  4,   4,  56],
        [  7,  42,  22]],

       [[546,   1,  12],
        [  5,  15,  62],
        [ 25,  25,  24]]])

In [74]:
#to convert the 3-D to 2-D array
array26 = np.ones((2,3,4))
array26

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [75]:
array26.size

24

In [76]:
array26.reshape(6,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [78]:
array27 = np.array([1,2,3,4,5,6,7,8])
array27.size

8

In [79]:
array27.resize(2,3)

In [80]:
array27

array([[1, 2, 3],
       [4, 5, 6]])

In [108]:
array28 = np.array([1,2,3,4,5,6,7,8])# we can do resize only one time but we can do reshape many times
#the main difference between reshape and resize is that reshape should be the proper multiple of the no. of elements in array
# and resize can be th proper or not proper multiple of no. of element
array28.resize(2,5)
array28

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 0, 0]])

In [85]:
array29 = np.array([1,2,3,4,5,6,7,8])

In [89]:
np.max(array29)# tells the largest element

np.int64(8)

In [90]:
np.argmax(array29)# tells the index of largest element

np.int64(7)

In [91]:
array30 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
np.max(array30)

np.int64(10)

In [92]:
np.argmax(array30)# in 3d array it gives index of maximm element according to 1-d array so it convert 2d into 1d before indexing

np.int64(9)

In [106]:
array30.flatten()# convert 2 d array to 1 d array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
np.argmax(array30)

np.int64(9)

In [102]:
np.max(array30, axis=1)# checks the  maximum element in the rows

array([ 5, 10])

In [103]:
np.max(array30, axis=0)# checks the maximum in the colums

array([ 6,  7,  8,  9, 10])

In [104]:
np.sum(array30, axis=1)# gives the sum of each elment in each row

array([15, 40])

In [109]:
np.sum(array30, axis=0)# gives the sum of each elment in each columns

array([ 7,  9, 11, 13, 15])

In [114]:
array31 = np.ones(10)

In [115]:
array31

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [116]:
np.resize(array31, (4,7))


array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [118]:
np.resize(array31,(50))

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [122]:
#example 1
expenses = np.array([
    [200, 340, 230, 150, 450], #food
    [100, 350, 120, 600, 244], #travel
    [300, 450, 256, 800, 679]  #shopping
])

In [171]:
print('total expense: ',np.sum(expenses))# these operations are very fast
print('category wise sum: ',np.sum(expenses, axis =1))
print('day wise total: ',np.sum(expenses, axis =0))
print('highest expense day: ', np.max(np.sum(expenses, axis=0)))

total expense:  5269
category wise sum:  [1370 1414 2485]
day wise total:  [ 600 1140  606 1550 1373]
highest expense day:  1550


In [125]:
#example 2
marks = np.array([34,56,65,78,87,65,66])

In [170]:
#where if like if else statement - takes less time- fast
grades =np.where(marks >= 75, "A", 
        np.where(marks >= 55, "B",
        np.where(marks >= 40, "C",  "Fail")))

In [130]:
print(grades)

['Fail' 'B' 'B' 'A' 'A' 'B' 'B']


In [132]:
print(marks>60)#gives boolean values

[False False  True  True  True  True  True]


In [133]:
# to print the marks greater than 60
print(marks[marks>60])

[65 78 87 65 66]


In [134]:
print(marks[(marks>60) & (marks<80)])

[65 78 65 66]


In [135]:
np.mean(marks)

np.float64(64.42857142857143)

In [137]:
np.median(marks)

np.float64(65.0)

In [144]:
#standard deviation - how much data is spreaded
np.std(marks)

np.float64(15.55503724436137)

In [145]:
check = np.ones(20)

In [146]:
np.std(check)

np.float64(0.0)

In [147]:
check[5] = 6

In [148]:
np.std(check)

np.float64(1.0897247358851685)

In [15]:
arr1=np.array([1,2,3,4])

In [16]:
# to check how much time array takes to do that operation
%timeit arr1*2

2.75 μs ± 76.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [17]:
%timeit [i*2 for i in arr1]# so loop takes more time that simple multiplication so we use vectorization

4.68 μs ± 330 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [165]:
np.sqrt(arr1)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [167]:
np.exp(arr1)# exp is for e^element of array

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [163]:
np.square(arr1)

array([ 1,  4,  9, 16])

In [164]:
np.split(arr1,2)# here 2 is the index where we want to split the array

[array([1, 2]), array([3, 4])]